// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANND0c96c3J6m5iz76EcF9V4N80hm2R90',
    appId: '1:360401967253:web:193bc0a8d1578b1943a39c',
    messagingSenderId: '360401967253',
    projectId: 'open-rooms',
    authDomain: 'open-rooms.firebaseapp.com',
    databaseURL: 'https://open-rooms-default-rtdb.firebaseio.com',
    storageBucket: 'open-rooms.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTOvlYfuCXjLQJ-R5BfY-6zQrXQdiSPH4',
    appId: '1:360401967253:android:f0f4bc9f28d2bfce43a39c',
    messagingSenderId: '360401967253',
    projectId: 'open-rooms',
    databaseURL: 'https://open-rooms-default-rtdb.firebaseio.com',
    storageBucket: 'open-rooms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXK2SHIth-WDVFxFsCO5zQIOBXVETdw1o',
    appId: '1:360401967253:ios:f633f008c931344b43a39c',
    messagingSenderId: '360401967253',
    projectId: 'open-rooms',
    databaseURL: 'https://open-rooms-default-rtdb.firebaseio.com',
    storageBucket: 'open-rooms.appspot.com',
    iosBundleId: 'com.josval.openRooms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXK2SHIth-WDVFxFsCO5zQIOBXVETdw1o',
    appId: '1:360401967253:ios:f633f008c931344b43a39c',
    messagingSenderId: '360401967253',
    projectId: 'open-rooms',
    databaseURL: 'https://open-rooms-default-rtdb.firebaseio.com',
    storageBucket: 'open-rooms.appspot.com',
    iosBundleId: 'com.josval.openRooms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANND0c96c3J6m5iz76EcF9V4N80hm2R90',
    appId: '1:360401967253:web:0b96d56ff313df5e43a39c',
    messagingSenderId: '360401967253',
    projectId: 'open-rooms',
    authDomain: 'open-rooms.firebaseapp.com',
    databaseURL: 'https://open-rooms-default-rtdb.firebaseio.com',
    storageBucket: 'open-rooms.appspot.com',
  );
}
